---
name: Task Tracker
about: Use this template to track tasks with subtasks, assignees, labels, and dates
title: "[Task] <Insert task title here>"
labels: [task, needs-triage]
assignees: ''
---

## 📌 Summary

<!-- Provide a short summary of the task -->

## ✅ Subtasks

- [ ] Subtask 1 — _@assignee_
- [ ] Subtask 2 — _@assignee_
- [ ] Subtask 3 — _@assignee_

## 🗂 Labels

<!-- Add or suggest labels to categorize this task -->
Suggested Labels: `frontend`, `backend`, `documentation`, `urgent`, `bug`, `enhancement`

## 🗓️ Timeline

| Start Date | Due Date |
|------------|----------|
| YYYY-MM-DD | YYYY-MM-DD |

## 🧠 Context / Background

<!-- Add relevant information, links, context, or references -->

## 📊 Progress Tracker

| Status       | Owner     | Notes                     |
|--------------|-----------|---------------------------|
| Not Started  | @person1  |                           |
| In Progress  | @person2  | Working on integration    |
| Blocked      | @person3  | Waiting on API response   |
| Completed    |           |                           |

## 💬 Comments

<!-- Add any additional notes or considerations -->
